language: erlang
dist: trusty
sudo: required
addons:
    apt:
        packages:
        - libpam0g-dev
        - libexpat1-dev
        - odbc-postgresql
        - slapd
        - ldap-utils
before_install:
        - curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - tools/travis-generate-pass.sh
        - tools/configure $REL_CONFIG
install:
        - echo "skip"
before_script:
        - tools/travis-setup-db.sh
        - if [ $PRESET = 'ldap_mnesia' ]; then sudo tools/travis-setup-ldap.sh; fi
script: tools/travis-test.sh -p $PRESET -s false -c false

after_failure:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - if [ -s _build/mim1/rel/mongooseim/log/crash.log ]; then cat _build/mim1/rel/mongooseim/log/crash.log; fi
        - if [ -s _build/mim2/rel/mongooseim/log/crash.log ]; then cat _build/mim2/rel/mongooseim/log/crash.log; fi
        - tail -100 _build/mim1/rel/mongooseim/log/ejabberd.log
        - tail -100 _build/mim2/rel/mongooseim/log/ejabberd.log

after_success:
        - ./rebar3 coveralls send
        - if [ $PRESET = 'internal_mnesia' ] && [ $TRAVIS_OTP_RELEASE = "18.3" ]; then tools/travis-build-and-push-docker.sh; fi

after_script:
        - sudo pip install awscli --ignore-installed six
        - if [ $TRAVIS_SECURE_ENV_VARS == 'true' ]; then tools/travis-upload-to-s3.sh; fi

services:
        - redis-server
        - docker

branches:
        only:
                - master
                - stable
                - /^rel\-\d+\.\d+$/
                - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

otp_release:
        - 18.3
env:
        - PRESET=mssql_mnesia DB=mssql REL_CONFIG=with-odbc

notifications:
    webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
        - http://tide.erlang-solutions.com/api/travis_ci/events
    on_start: always

cache:
        directories:
                - $HOME/.cache/rebar3

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file: mongooseim-$TRAVIS_BRANCH.OTP-$TRAVIS_OTP_RELEASE.$(lsb_release -is | tr "A-Z" "a-z").$(lsb_release -rs).$(uname -m).tar.bz2
  on:
    tags: true
    condition: "$PRESET.$TRAVIS_OTP_RELEASE = internal_mnesia.18.3"

